import type { IQuizDetail } from "@/app/types";
import { Difficulty } from "@/app/types";

export const dummyQuizDetail: IQuizDetail = {
    uuid: "quiz-uuid-001",
    quiz_title: "Latihan Aljabar Lanjutan",
    difficulty: Difficulty.HARD,
    duration: 60,
    total_questions: 10,
    subject_name: "Matematika",
    attempt: null,
    questions: [
        {
            idQuestion: 1,
            uuid: "q-uuid-001",
            question_text: "Tentukan nilai $x$ yang memenuhi persamaan $2x^2 - 5x + 3 = 0$.",
            question_image: "",
            difficulty: Difficulty.MEDIUM,
            poin: 10,
            options: [
                { idOption: 1, uuid: "opt-1-1", option_text: "$x = \\frac{3}{2}$ atau $x = 1$", option_image: "" },
                { idOption: 2, uuid: "opt-1-2", option_text: "$x = 3$ atau $x = \\frac{1}{2}$", option_image: "" },
                { idOption: 3, uuid: "opt-1-3", option_text: "$x = -\\frac{3}{2}$ atau $x = -1$", option_image: "" },
                { idOption: 4, uuid: "opt-1-4", option_text: "$x = 2$ atau $x = \\frac{3}{4}$", option_image: "" },
            ],
        },
        {
            idQuestion: 2,
            uuid: "q-uuid-002",
            question_text: "Jika $f(x) = 3x^2 + 2x - 1$, maka nilai dari $f(2)$ adalah...",
            question_image: "",
            difficulty: Difficulty.EASY,
            poin: 10,
            options: [
                { idOption: 5, uuid: "opt-2-1", option_text: "15", option_image: "" },
                { idOption: 6, uuid: "opt-2-2", option_text: "12", option_image: "" },
                { idOption: 7, uuid: "opt-2-3", option_text: "11", option_image: "" },
                { idOption: 8, uuid: "opt-2-4", option_text: "13", option_image: "" },
            ],
        },
        {
            idQuestion: 3,
            uuid: "q-uuid-003",
            question_text: "Diketahui sistem persamaan linear: $x + 2y = 7$ dan $3x - y = 1$. Nilai dari $x + y$ adalah...",
            question_image: "",
            difficulty: Difficulty.MEDIUM,
            poin: 10,
            options: [
                { idOption: 9,  uuid: "opt-3-1", option_text: "4", option_image: "" },
                { idOption: 10, uuid: "opt-3-2", option_text: "3", option_image: "" },
                { idOption: 11, uuid: "opt-3-3", option_text: "5", option_image: "" },
                { idOption: 12, uuid: "opt-3-4", option_text: "6", option_image: "" },
            ],
        },
        {
            idQuestion: 4,
            uuid: "q-uuid-004",
            question_text: "Hasil dari $\\log_2 32 + \\log_3 9$ adalah...",
            question_image: "",
            difficulty: Difficulty.EASY,
            poin: 10,
            options: [
                { idOption: 13, uuid: "opt-4-1", option_text: "7", option_image: "" },
                { idOption: 14, uuid: "opt-4-2", option_text: "9", option_image: "" },
                { idOption: 15, uuid: "opt-4-3", option_text: "6", option_image: "" },
                { idOption: 16, uuid: "opt-4-4", option_text: "8", option_image: "" },
            ],
        },
        {
            idQuestion: 5,
            uuid: "q-uuid-005",
            question_text: "Sebuah deret aritmatika memiliki suku pertama 3 dan beda 4. Suku ke-10 dari deret tersebut adalah...",
            question_image: "",
            difficulty: Difficulty.MEDIUM,
            poin: 10,
            options: [
                { idOption: 17, uuid: "opt-5-1", option_text: "37", option_image: "" },
                { idOption: 18, uuid: "opt-5-2", option_text: "39", option_image: "" },
                { idOption: 19, uuid: "opt-5-3", option_text: "40", option_image: "" },
                { idOption: 20, uuid: "opt-5-4", option_text: "43", option_image: "" },
            ],
        },
        {
            idQuestion: 6,
            uuid: "q-uuid-006",
            question_text: "Nilai dari $\\int_0^2 (3x^2 + 2x) \\, dx$ adalah...",
            question_image: "",
            difficulty: Difficulty.HARD,
            poin: 10,
            options: [
                { idOption: 21, uuid: "opt-6-1", option_text: "12", option_image: "" },
                { idOption: 22, uuid: "opt-6-2", option_text: "10", option_image: "" },
                { idOption: 23, uuid: "opt-6-3", option_text: "14", option_image: "" },
                { idOption: 24, uuid: "opt-6-4", option_text: "16", option_image: "" },
            ],
        },
        {
            idQuestion: 7,
            uuid: "q-uuid-007",
            question_text: "Tentukan determinan dari matriks $A = \\begin{pmatrix} 3 & 2 \\\\ 5 & 4 \\end{pmatrix}$.",
            question_image: "",
            difficulty: Difficulty.EASY,
            poin: 10,
            options: [
                { idOption: 25, uuid: "opt-7-1", option_text: "2", option_image: "" },
                { idOption: 26, uuid: "opt-7-2", option_text: "-2", option_image: "" },
                { idOption: 27, uuid: "opt-7-3", option_text: "4", option_image: "" },
                { idOption: 28, uuid: "opt-7-4", option_text: "22", option_image: "" },
            ],
        },
        {
            idQuestion: 8,
            uuid: "q-uuid-008",
            question_text: "Jumlah semua bilangan asli dari 1 hingga 100 adalah...",
            question_image: "",
            difficulty: Difficulty.EASY,
            poin: 10,
            options: [
                { idOption: 29, uuid: "opt-8-1", option_text: "5050", option_image: "" },
                { idOption: 30, uuid: "opt-8-2", option_text: "5000", option_image: "" },
                { idOption: 31, uuid: "opt-8-3", option_text: "4950", option_image: "" },
                { idOption: 32, uuid: "opt-8-4", option_text: "5100", option_image: "" },
            ],
        },
        {
            idQuestion: 9,
            uuid: "q-uuid-009",
            question_text: "Dari 6 orang akan dipilih 2 orang. Banyaknya kombinasi yang mungkin adalah...",
            question_image: "",
            difficulty: Difficulty.MEDIUM,
            poin: 10,
            options: [
                { idOption: 33, uuid: "opt-9-1", option_text: "15", option_image: "" },
                { idOption: 34, uuid: "opt-9-2", option_text: "30", option_image: "" },
                { idOption: 35, uuid: "opt-9-3", option_text: "12", option_image: "" },
                { idOption: 36, uuid: "opt-9-4", option_text: "18", option_image: "" },
            ],
        },
        {
            idQuestion: 10,
            uuid: "q-uuid-010",
            question_text: "Nilai dari $\\sin 30° + \\cos 60° - \\tan 45°$ adalah...",
            question_image: "",
            difficulty: Difficulty.EASY,
            poin: 10,
            options: [
                { idOption: 37, uuid: "opt-10-1", option_text: "0", option_image: "" },
                { idOption: 38, uuid: "opt-10-2", option_text: "1", option_image: "" },
                { idOption: 39, uuid: "opt-10-3", option_text: "-1", option_image: "" },
                { idOption: 40, uuid: "opt-10-4", option_text: "0.5", option_image: "" },
            ],
        },
    ],
};
