import type { IQuizResult, IQuizReview, IStudentProgress } from "@/app/types";
import { Difficulty } from "@/app/types";

// ─── RESULT ────────────────────────────────────────────────
export const dummyQuizResult: IQuizResult = {
    quiz_uuid: "quiz-uuid-001",
    quiz_title: "Latihan Aljabar Lanjutan",
    subject_name: "Matematika",
    difficulty: Difficulty.HARD,
    score: {
        uuid: "score-uuid-001",
        total_questions: 10,
        correct: 8,
        wrong: 1,
        skipped: 1,
        score: 80,
        accuracy: 88.9,
        start_time: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
        finished_time: new Date().toISOString(),
        duration_used: 48,
    },
    rank: 4,
    xp_earned: 240,
    question_breakdown: [
        { question_index: 1, question_text: "Tentukan nilai $x$ yang memenuhi persamaan $2x^2 - 5x + 3 = 0$.", selected_option_id: 1, is_correct: true, is_skipped: false },
        { question_index: 2, question_text: "Jika $f(x) = 3x^2 + 2x - 1$, maka nilai dari $f(2)$ adalah...", selected_option_id: 5, is_correct: true, is_skipped: false },
        { question_index: 3, question_text: "Diketahui sistem persamaan linear...", selected_option_id: 9, is_correct: true, is_skipped: false },
        { question_index: 4, question_text: "Hasil dari $\\log_2 32 + \\log_3 9$ adalah...", selected_option_id: 13, is_correct: true, is_skipped: false },
        { question_index: 5, question_text: "Sebuah deret aritmatika memiliki suku pertama 3...", selected_option_id: 18, is_correct: false, is_skipped: false },
        { question_index: 6, question_text: "Nilai dari $\\int_0^2 (3x^2 + 2x) \\, dx$ adalah...", selected_option_id: 21, is_correct: true, is_skipped: false },
        { question_index: 7, question_text: "Tentukan determinan dari matriks $A$...", selected_option_id: 25, is_correct: true, is_skipped: false },
        { question_index: 8, question_text: "Jumlah semua bilangan asli dari 1 hingga 100 adalah...", selected_option_id: 29, is_correct: true, is_skipped: false },
        { question_index: 9, question_text: "Dari 6 orang akan dipilih 2 orang...", selected_option_id: 33, is_correct: true, is_skipped: false },
        { question_index: 10, question_text: "Nilai dari $\\sin 30° + \\cos 60° - \\tan 45°$ adalah...", selected_option_id: null, is_correct: false, is_skipped: true },
    ],
};

// ─── REVIEW ────────────────────────────────────────────────
export const dummyQuizReview: IQuizReview = {
    quiz_uuid: "quiz-uuid-001",
    quiz_title: "Latihan Aljabar Lanjutan",
    subject_name: "Matematika",
    difficulty: Difficulty.HARD,
    total_questions: 10,
    correct_count: 8,
    wrong_count: 1,
    skipped_count: 1,
    score: 80,
    questions: [
        {
            idQuestion: 1, uuid: "q-uuid-001", question_index: 1,
            question_text: "Tentukan nilai $x$ yang memenuhi persamaan $2x^2 - 5x + 3 = 0$.",
            question_image: "", difficulty: Difficulty.MEDIUM, poin: 10,
            options: [
                { idOption: 1, uuid: "opt-1-1", option_text: "$x = \\frac{3}{2}$ atau $x = 1$", option_image: "", is_correct: true },
                { idOption: 2, uuid: "opt-1-2", option_text: "$x = 3$ atau $x = \\frac{1}{2}$", option_image: "", is_correct: false },
                { idOption: 3, uuid: "opt-1-3", option_text: "$x = -\\frac{3}{2}$ atau $x = -1$", option_image: "", is_correct: false },
                { idOption: 4, uuid: "opt-1-4", option_text: "$x = 2$ atau $x = \\frac{3}{4}$", option_image: "", is_correct: false },
            ],
            selected_option_id: 1, correct_option_id: 1, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 2, uuid: "q-uuid-002", question_index: 2,
            question_text: "Jika $f(x) = 3x^2 + 2x - 1$, maka nilai dari $f(2)$ adalah...",
            question_image: "", difficulty: Difficulty.EASY, poin: 10,
            options: [
                { idOption: 5, uuid: "opt-2-1", option_text: "15", option_image: "", is_correct: false },
                { idOption: 6, uuid: "opt-2-2", option_text: "12", option_image: "", is_correct: false },
                { idOption: 7, uuid: "opt-2-3", option_text: "11", option_image: "", is_correct: true },
                { idOption: 8, uuid: "opt-2-4", option_text: "13", option_image: "", is_correct: false },
            ],
            selected_option_id: 5, correct_option_id: 7, is_correct: false, is_skipped: false, is_marked_review: true,
        },
        {
            idQuestion: 3, uuid: "q-uuid-003", question_index: 3,
            question_text: "Diketahui sistem persamaan linear: $x + 2y = 7$ dan $3x - y = 1$. Nilai dari $x + y$ adalah...",
            question_image: "", difficulty: Difficulty.MEDIUM, poin: 10,
            options: [
                { idOption: 9,  uuid: "opt-3-1", option_text: "4", option_image: "", is_correct: false },
                { idOption: 10, uuid: "opt-3-2", option_text: "3", option_image: "", is_correct: true },
                { idOption: 11, uuid: "opt-3-3", option_text: "5", option_image: "", is_correct: false },
                { idOption: 12, uuid: "opt-3-4", option_text: "6", option_image: "", is_correct: false },
            ],
            selected_option_id: 10, correct_option_id: 10, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 4, uuid: "q-uuid-004", question_index: 4,
            question_text: "Hasil dari $\\log_2 32 + \\log_3 9$ adalah...",
            question_image: "", difficulty: Difficulty.EASY, poin: 10,
            options: [
                { idOption: 13, uuid: "opt-4-1", option_text: "7", option_image: "", is_correct: true },
                { idOption: 14, uuid: "opt-4-2", option_text: "9", option_image: "", is_correct: false },
                { idOption: 15, uuid: "opt-4-3", option_text: "6", option_image: "", is_correct: false },
                { idOption: 16, uuid: "opt-4-4", option_text: "8", option_image: "", is_correct: false },
            ],
            selected_option_id: 13, correct_option_id: 13, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 5, uuid: "q-uuid-005", question_index: 5,
            question_text: "Sebuah deret aritmatika memiliki suku pertama 3 dan beda 4. Suku ke-10 dari deret tersebut adalah...",
            question_image: "", difficulty: Difficulty.MEDIUM, poin: 10,
            options: [
                { idOption: 17, uuid: "opt-5-1", option_text: "37", option_image: "", is_correct: false },
                { idOption: 18, uuid: "opt-5-2", option_text: "39", option_image: "", is_correct: true },
                { idOption: 19, uuid: "opt-5-3", option_text: "40", option_image: "", is_correct: false },
                { idOption: 20, uuid: "opt-5-4", option_text: "43", option_image: "", is_correct: false },
            ],
            selected_option_id: 17, correct_option_id: 18, is_correct: false, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 6, uuid: "q-uuid-006", question_index: 6,
            question_text: "Nilai dari $\\int_0^2 (3x^2 + 2x) \\, dx$ adalah...",
            question_image: "", difficulty: Difficulty.HARD, poin: 10,
            options: [
                { idOption: 21, uuid: "opt-6-1", option_text: "12", option_image: "", is_correct: true },
                { idOption: 22, uuid: "opt-6-2", option_text: "10", option_image: "", is_correct: false },
                { idOption: 23, uuid: "opt-6-3", option_text: "14", option_image: "", is_correct: false },
                { idOption: 24, uuid: "opt-6-4", option_text: "16", option_image: "", is_correct: false },
            ],
            selected_option_id: 21, correct_option_id: 21, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 7, uuid: "q-uuid-007", question_index: 7,
            question_text: "Tentukan determinan dari matriks $A = \\begin{pmatrix} 3 & 2 \\\\ 5 & 4 \\end{pmatrix}$.",
            question_image: "", difficulty: Difficulty.EASY, poin: 10,
            options: [
                { idOption: 25, uuid: "opt-7-1", option_text: "2", option_image: "", is_correct: true },
                { idOption: 26, uuid: "opt-7-2", option_text: "-2", option_image: "", is_correct: false },
                { idOption: 27, uuid: "opt-7-3", option_text: "4", option_image: "", is_correct: false },
                { idOption: 28, uuid: "opt-7-4", option_text: "22", option_image: "", is_correct: false },
            ],
            selected_option_id: 25, correct_option_id: 25, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 8, uuid: "q-uuid-008", question_index: 8,
            question_text: "Jumlah semua bilangan asli dari 1 hingga 100 adalah...",
            question_image: "", difficulty: Difficulty.EASY, poin: 10,
            options: [
                { idOption: 29, uuid: "opt-8-1", option_text: "5050", option_image: "", is_correct: true },
                { idOption: 30, uuid: "opt-8-2", option_text: "5000", option_image: "", is_correct: false },
                { idOption: 31, uuid: "opt-8-3", option_text: "4950", option_image: "", is_correct: false },
                { idOption: 32, uuid: "opt-8-4", option_text: "5100", option_image: "", is_correct: false },
            ],
            selected_option_id: 29, correct_option_id: 29, is_correct: true, is_skipped: false, is_marked_review: false,
        },
        {
            idQuestion: 9, uuid: "q-uuid-009", question_index: 9,
            question_text: "Dari 6 orang akan dipilih 2 orang. Banyaknya kombinasi yang mungkin adalah...",
            question_image: "", difficulty: Difficulty.MEDIUM, poin: 10,
            options: [
                { idOption: 33, uuid: "opt-9-1", option_text: "15", option_image: "", is_correct: true },
                { idOption: 34, uuid: "opt-9-2", option_text: "30", option_image: "", is_correct: false },
                { idOption: 35, uuid: "opt-9-3", option_text: "12", option_image: "", is_correct: false },
                { idOption: 36, uuid: "opt-9-4", option_text: "18", option_image: "", is_correct: false },
            ],
            selected_option_id: 33, correct_option_id: 33, is_correct: true, is_skipped: false, is_marked_review: true,
        },
        {
            idQuestion: 10, uuid: "q-uuid-010", question_index: 10,
            question_text: "Nilai dari $\\sin 30° + \\cos 60° - \\tan 45°$ adalah...",
            question_image: "", difficulty: Difficulty.EASY, poin: 10,
            options: [
                { idOption: 37, uuid: "opt-10-1", option_text: "0", option_image: "", is_correct: true },
                { idOption: 38, uuid: "opt-10-2", option_text: "1", option_image: "", is_correct: false },
                { idOption: 39, uuid: "opt-10-3", option_text: "-1", option_image: "", is_correct: false },
                { idOption: 40, uuid: "opt-10-4", option_text: "0.5", option_image: "", is_correct: false },
            ],
            selected_option_id: null, correct_option_id: 37, is_correct: false, is_skipped: true, is_marked_review: false,
        },
    ],
};

// ─── PROGRESS ──────────────────────────────────────────────
export const dummyStudentProgress: IStudentProgress = {
    overall: {
        average_score: 82,
        learning_streak: 7,
        completed_quiz: 18,
        total_quiz: 27,
        completion_rate: 67,
        average_accuracy: 78,
        total_time_spent: 540,
    },
    subject_progress: [
        { subject_name: "Matematika",      total_quiz: 7, completed_quiz: 6, average_score: 91, mastery_percentage: 85, trend: "UP" },
        { subject_name: "Fisika",          total_quiz: 7, completed_quiz: 5, average_score: 79, mastery_percentage: 71, trend: "UP" },
        { subject_name: "Kimia",           total_quiz: 7, completed_quiz: 4, average_score: 75, mastery_percentage: 64, trend: "STABLE" },
        { subject_name: "Bahasa Indonesia",total_quiz: 7, completed_quiz: 4, average_score: 68, mastery_percentage: 57, trend: "DOWN" },
        { subject_name: "Bahasa Inggris",  total_quiz: 6, completed_quiz: 3, average_score: 72, mastery_percentage: 55, trend: "UP" },
        { subject_name: "Biologi",         total_quiz: 5, completed_quiz: 2, average_score: 70, mastery_percentage: 40, trend: "STABLE" },
    ],
    monthly_performance: [
        { month: "Feb", average_score: 65, quizzes_done: 3 },
        { month: "Mar", average_score: 70, quizzes_done: 4 },
        { month: "Apr", average_score: 74, quizzes_done: 5 },
        { month: "Mei", average_score: 78, quizzes_done: 4 },
        { month: "Jun", average_score: 80, quizzes_done: 6 },
        { month: "Jul", average_score: 82, quizzes_done: 4 },
    ],
    accuracy_trend: [
        { week: "W1", accuracy: 68 },
        { week: "W2", accuracy: 72 },
        { week: "W3", accuracy: 75 },
        { week: "W4", accuracy: 79 },
        { week: "W5", accuracy: 74 },
        { week: "W6", accuracy: 82 },
        { week: "W7", accuracy: 78 },
        { week: "W8", accuracy: 85 },
    ],
    weak_topics: [
        { topic: "Teks Argumentasi",   subject: "Bahasa Indonesia", accuracy: 52, attempts: 3 },
        { topic: "Kalimat Efektif",    subject: "Bahasa Indonesia", accuracy: 55, attempts: 2 },
        { topic: "Optika Geometri",    subject: "Fisika",           accuracy: 58, attempts: 4 },
        { topic: "Kimia Organik",      subject: "Kimia",            accuracy: 61, attempts: 3 },
        { topic: "Grammar & Tenses",   subject: "Bahasa Inggris",   accuracy: 63, attempts: 2 },
    ],
    strong_topics: [
        { topic: "Aljabar Lanjutan",   subject: "Matematika",  accuracy: 96, attempts: 5 },
        { topic: "Persamaan Kuadrat",  subject: "Matematika",  accuracy: 92, attempts: 4 },
        { topic: "Stoikiometri",       subject: "Kimia",       accuracy: 90, attempts: 3 },
        { topic: "Mekanika",           subject: "Fisika",      accuracy: 88, attempts: 4 },
        { topic: "Logaritma",          subject: "Matematika",  accuracy: 87, attempts: 3 },
    ],
    recent_activity: [
        { id: "a1", action: "COMPLETED_QUIZ", quiz_title: "Latihan Aljabar Lanjutan",  subject_name: "Matematika", score: 92, created_at: new Date(Date.now() - 2 * 3600_000).toISOString() },
        { id: "a2", action: "STARTED_QUIZ",   quiz_title: "Trigonometri & Identitas",  subject_name: "Matematika", created_at: new Date(Date.now() - 30 * 60_000).toISOString() },
        { id: "a3", action: "REVIEWED_QUIZ",  quiz_title: "Teks Argumentasi & Persuasi", subject_name: "Bahasa Indonesia", score: 68, created_at: new Date(Date.now() - 25 * 3600_000).toISOString() },
        { id: "a4", action: "COMPLETED_QUIZ", quiz_title: "Gelombang Elektromagnetik", subject_name: "Fisika", score: 76, created_at: new Date(Date.now() - 50 * 3600_000).toISOString() },
    ],
};
