import type {
    IStudentDashboard,
} from "@/app/types";
import { Difficulty } from "@/app/types";

export const dummyStudentDashboard: IStudentDashboard = {
    student: {
        uuid: "student-uuid-001",
        full_name: "Darian Ali Prasetyo",
        userName: "darian_ali",
        photoProfile: "/public/user_image/user_profile.jpg",
        class_name: "Kelas XI IPA 2",
        class_program: "UTBK",
    },
    stats: {
        average_score: 82,
        weekly_progress: 12,
        current_rank: 4,
        current_streak: 7,
        completed_quiz: 18,
        remaining_quiz: 9,
        average_accuracy: 78,
        time_spent: 540, // 9 hours in minutes
    },
    strongest_subject: {
        subject_name: "Matematika",
        average_score: 91,
    },
    weakest_subject: {
        subject_name: "Bahasa Indonesia",
        average_score: 68,
    },
    recent_quizzes: [
        {
            quiz_uuid: "quiz-uuid-001",
            quiz_title: "Latihan Aljabar Lanjutan",
            subject_name: "Matematika",
            score: 92,
            correct: 23,
            wrong: 2,
            total_questions: 25,
            difficulty: Difficulty.HARD,
            finished_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
            duration_used: 48,
        },
        {
            quiz_uuid: "quiz-uuid-002",
            quiz_title: "Teks Argumentasi & Persuasi",
            subject_name: "Bahasa Indonesia",
            score: 68,
            correct: 17,
            wrong: 8,
            total_questions: 25,
            difficulty: Difficulty.MEDIUM,
            finished_time: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
            duration_used: 55,
        },
        {
            quiz_uuid: "quiz-uuid-003",
            quiz_title: "Gelombang Elektromagnetik",
            subject_name: "Fisika",
            score: 76,
            correct: 19,
            wrong: 6,
            total_questions: 25,
            difficulty: Difficulty.MEDIUM,
            finished_time: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
            duration_used: 62,
        },
        {
            quiz_uuid: "quiz-uuid-004",
            quiz_title: "Stoikiometri Reaksi",
            subject_name: "Kimia",
            score: 84,
            correct: 21,
            wrong: 4,
            total_questions: 25,
            difficulty: Difficulty.EASY,
            finished_time: new Date(Date.now() - 74 * 60 * 60 * 1000).toISOString(),
            duration_used: 35,
        },
    ],
    in_progress_quizzes: [
        {
            quiz_uuid: "quiz-uuid-005",
            quiz_title: "Trigonometri & Identitas",
            subject_name: "Matematika",
            difficulty: Difficulty.HARD,
            duration: 60,
            total_questions: 30,
            start_time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
            attempt_id: 42,
        },
    ],
    subject_mastery: [
        { subject_name: "Matematika", mastery_percentage: 85, completed: 6, total: 7, average_score: 91 },
        { subject_name: "Fisika", mastery_percentage: 71, completed: 5, total: 7, average_score: 79 },
        { subject_name: "Kimia", mastery_percentage: 64, completed: 4, total: 7, average_score: 75 },
        { subject_name: "Bahasa Indonesia", mastery_percentage: 57, completed: 4, total: 7, average_score: 68 },
        { subject_name: "Bahasa Inggris", mastery_percentage: 43, completed: 3, total: 7, average_score: 72 },
    ],
    weekly_scores: [
        { day: "Sen", average_score: 75, quizzes_done: 1 },
        { day: "Sel", average_score: 82, quizzes_done: 2 },
        { day: "Rab", average_score: 0,  quizzes_done: 0 },
        { day: "Kam", average_score: 88, quizzes_done: 1 },
        { day: "Jum", average_score: 92, quizzes_done: 2 },
        { day: "Sab", average_score: 79, quizzes_done: 1 },
        { day: "Min", average_score: 0,  quizzes_done: 0 },
    ],
    recent_activities: [
        { id: "act-1", action: "COMPLETED_QUIZ", quiz_title: "Latihan Aljabar Lanjutan", subject_name: "Matematika", score: 92, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
        { id: "act-2", action: "STARTED_QUIZ",   quiz_title: "Trigonometri & Identitas",  subject_name: "Matematika", created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
        { id: "act-3", action: "REVIEWED_QUIZ",  quiz_title: "Teks Argumentasi & Persuasi", subject_name: "Bahasa Indonesia", score: 68, created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString() },
        { id: "act-4", action: "COMPLETED_QUIZ", quiz_title: "Gelombang Elektromagnetik",  subject_name: "Fisika", score: 76, created_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString() },
        { id: "act-5", action: "COMPLETED_QUIZ", quiz_title: "Stoikiometri Reaksi",        subject_name: "Kimia",  score: 84, created_at: new Date(Date.now() - 74 * 60 * 60 * 1000).toISOString() },
    ],
};
