import type { ClassOverview, Student } from "@/types/student";

export const students: Student[] = [
  {
    id: "s1",
    name: "Nadia Rahmawati",
    avatarInitials: "NR",
    className: "Class 10-A",
    classId: "10a",
    lastActiveAt: "2026-07-16T09:00:00.000Z",
    averageScore: 92,
    completionRate: 96,
    streakDays: 14,
    trend: { value: 6, direction: "up" },
    sparkline: [
      { label: "W1", value: 78 },
      { label: "W2", value: 82 },
      { label: "W3", value: 85 },
      { label: "W4", value: 88 },
      { label: "W5", value: 92 },
    ],
    strongestSubject: "math",
    strongestSubjectScore: 94,
    weakestSubject: "math",
    weakestSubjectScore: 71,
    atRisk: false,
    email: "nadia.rahmawati@student.school.id",
  },
  {
    id: "s2",
    name: "Bintang Aditya",
    avatarInitials: "BA",
    className: "Class 10-A",
    classId: "10a",
    lastActiveAt: "2026-07-16T08:00:00.000Z",
    averageScore: 88,
    completionRate: 90,
    streakDays: 11,
    trend: { value: 2, direction: "up" },
    sparkline: [
      { label: "W1", value: 80 },
      { label: "W2", value: 83 },
      { label: "W3", value: 84 },
      { label: "W4", value: 86 },
      { label: "W5", value: 88 },
    ],
    strongestSubject: "physics",
    strongestSubjectScore: 90,
    weakestSubject: "chemistry",
    weakestSubjectScore: 74,
    atRisk: false,
    email: "bintang.aditya@student.school.id",
  },
  {
    id: "s3",
    name: "Kirana Putri",
    avatarInitials: "KP",
    className: "Class 10-A",
    classId: "10a",
    lastActiveAt: "2026-07-15T14:30:00.000Z",
    averageScore: 85,
    completionRate: 88,
    streakDays: 6,
    trend: { value: 3, direction: "up" },
    sparkline: [
      { label: "W1", value: 76 },
      { label: "W2", value: 79 },
      { label: "W3", value: 81 },
      { label: "W4", value: 83 },
      { label: "W5", value: 85 },
    ],
    strongestSubject: "biology",
    strongestSubjectScore: 91,
    weakestSubject: "math",
    weakestSubjectScore: 76,
    atRisk: false,
    email: "kirana.putri@student.school.id",
  },
  {
    id: "s4",
    name: "Fajar Nugroho",
    avatarInitials: "FN",
    className: "Class 10-B",
    classId: "10b",
    lastActiveAt: "2026-07-13T11:00:00.000Z",
    averageScore: 63,
    completionRate: 54,
    streakDays: 0,
    trend: { value: 8, direction: "down" },
    sparkline: [
      { label: "W1", value: 74 },
      { label: "W2", value: 70 },
      { label: "W3", value: 68 },
      { label: "W4", value: 65 },
      { label: "W5", value: 63 },
    ],
    strongestSubject: "history",
    strongestSubjectScore: 77,
    weakestSubject: "math",
    weakestSubjectScore: 51,
    atRisk: true,
    email: "fajar.nugroho@student.school.id",
  },
  {
    id: "s5",
    name: "Salsabila Zahra",
    avatarInitials: "SZ",
    className: "Class 10-A",
    classId: "10a",
    lastActiveAt: "2026-07-16T07:15:00.000Z",
    averageScore: 79,
    completionRate: 82,
    streakDays: 4,
    trend: { value: 1, direction: "flat" },
    sparkline: [
      { label: "W1", value: 77 },
      { label: "W2", value: 78 },
      { label: "W3", value: 79 },
      { label: "W4", value: 78 },
      { label: "W5", value: 79 },
    ],
    strongestSubject: "chemistry",
    strongestSubjectScore: 85,
    weakestSubject: "physics",
    weakestSubjectScore: 69,
    atRisk: false,
    email: "salsabila.zahra@student.school.id",
  },
  {
    id: "s6",
    name: "Reza Firmansyah",
    avatarInitials: "RF",
    className: "Class 10-B",
    classId: "10b",
    lastActiveAt: "2026-07-16T06:40:00.000Z",
    averageScore: 81,
    completionRate: 85,
    streakDays: 9,
    trend: { value: 5, direction: "up" },
    sparkline: [
      { label: "W1", value: 70 },
      { label: "W2", value: 74 },
      { label: "W3", value: 77 },
      { label: "W4", value: 79 },
      { label: "W5", value: 81 },
    ],
    strongestSubject: "math",
    strongestSubjectScore: 87,
    weakestSubject: "biology",
    weakestSubjectScore: 72,
    atRisk: false,
    email: "reza.firmansyah@student.school.id",
  },
  {
    id: "s7",
    name: "Ayu Lestari",
    avatarInitials: "AL",
    className: "Class 10-B",
    classId: "10b",
    lastActiveAt: "2026-07-13T18:20:00.000Z",
    averageScore: 74,
    completionRate: 68,
    streakDays: 2,
    trend: { value: 8, direction: "down" },
    sparkline: [
      { label: "W1", value: 84 },
      { label: "W2", value: 81 },
      { label: "W3", value: 79 },
      { label: "W4", value: 76 },
      { label: "W5", value: 74 },
    ],
    strongestSubject: "history",
    strongestSubjectScore: 88,
    weakestSubject: "physics",
    weakestSubjectScore: 58,
    atRisk: false,
    email: "ayu.lestari@student.school.id",
  },
];

export const classOverview: ClassOverview = {
  className: "Class 10-A & 10-B",
  learnerCount: students.length,
  averageScore: Math.round(
    students.reduce((sum, s) => sum + s.averageScore, 0) / students.length
  ),
  risingCount: students.filter((s) => s.trend.direction === "up").length,
  topPerformer: { name: "Nadia Rahmawati", score: 92 },
  atRiskCount: students.filter((s) => s.atRisk).length,
  atRiskThreshold: 70,
  longestStreak: { name: "Nadia Rahmawati", days: 14 },
  averageCompletion: Math.round(
    students.reduce((sum, s) => sum + s.completionRate, 0) / students.length
  ),
};

export const classList = [
  { id: "all", label: "All classes" },
  { id: "10a", label: "Class 10-A" },
  { id: "10b", label: "Class 10-B" },
];
