import type { IStudentSubjectSummary, IStudentSubject } from "@/app/types";
import { Difficulty } from "@/app/types";

/** Untuk halaman daftar subject (/student/subjects) */
export const dummyStudentSubjects: IStudentSubjectSummary[] = [
    {
        uuid: "subject-uuid-001",
        subject_name: "Matematika",
        total_quiz: 7,
        completed_quiz: 6,
        average_score: 91,
        completion_percentage: 86,
    },
    {
        uuid: "subject-uuid-002",
        subject_name: "Fisika",
        total_quiz: 7,
        completed_quiz: 5,
        average_score: 79,
        completion_percentage: 71,
    },
    {
        uuid: "subject-uuid-003",
        subject_name: "Kimia",
        total_quiz: 7,
        completed_quiz: 4,
        average_score: 75,
        completion_percentage: 57,
    },
    {
        uuid: "subject-uuid-004",
        subject_name: "Bahasa Indonesia",
        total_quiz: 7,
        completed_quiz: 4,
        average_score: 68,
        completion_percentage: 57,
    },
    {
        uuid: "subject-uuid-005",
        subject_name: "Bahasa Inggris",
        total_quiz: 7,
        completed_quiz: 3,
        average_score: 72,
        completion_percentage: 43,
    },
    {
        uuid: "subject-uuid-006",
        subject_name: "Biologi",
        total_quiz: 5,
        completed_quiz: 2,
        average_score: 70,
        completion_percentage: 40,
    },
];

/** Untuk halaman detail subject (/student/subjects/[id]) */
export const dummyStudentSubjectDetail: IStudentSubject = {
    uuid: "subject-uuid-001",
    subject_name: "Matematika",
    total_quiz: 7,
    completed_quiz: 6,
    average_score: 91,
    completion_percentage: 86,
    estimated_time: 350,
    quizzes: [
        {
            uuid: "quiz-uuid-001",
            quiz_title: "Latihan Aljabar Lanjutan",
            difficulty: Difficulty.HARD,
            duration: 60,
            total_questions: 25,
            quiz_date: new Date("2026-07-10").toISOString(),
            student_status: "COMPLETED",
            last_score: 92,
            last_correct: 23,
            last_wrong: 2,
            attempt_id: 1,
            is_finished: true,
        },
        {
            uuid: "quiz-uuid-005",
            quiz_title: "Trigonometri & Identitas",
            difficulty: Difficulty.HARD,
            duration: 60,
            total_questions: 30,
            quiz_date: new Date("2026-07-12").toISOString(),
            student_status: "IN_PROGRESS",
            last_score: null,
            last_correct: null,
            last_wrong: null,
            attempt_id: 42,
            is_finished: false,
        },
        {
            uuid: "quiz-uuid-006",
            quiz_title: "Kalkulus Dasar — Turunan",
            difficulty: Difficulty.MEDIUM,
            duration: 45,
            total_questions: 20,
            quiz_date: new Date("2026-07-15").toISOString(),
            student_status: "NOT_STARTED",
            last_score: null,
            last_correct: null,
            last_wrong: null,
            attempt_id: null,
            is_finished: false,
        },
        {
            uuid: "quiz-uuid-007",
            quiz_title: "Statistika & Peluang",
            difficulty: Difficulty.EASY,
            duration: 30,
            total_questions: 15,
            quiz_date: new Date("2026-07-08").toISOString(),
            student_status: "COMPLETED",
            last_score: 88,
            last_correct: 13,
            last_wrong: 2,
            attempt_id: 5,
            is_finished: true,
        },
        {
            uuid: "quiz-uuid-008",
            quiz_title: "Persamaan Kuadrat",
            difficulty: Difficulty.MEDIUM,
            duration: 45,
            total_questions: 20,
            quiz_date: new Date("2026-07-05").toISOString(),
            student_status: "COMPLETED",
            last_score: 95,
            last_correct: 19,
            last_wrong: 1,
            attempt_id: 3,
            is_finished: true,
        },
        {
            uuid: "quiz-uuid-009",
            quiz_title: "Matriks & Determinan",
            difficulty: Difficulty.MEDIUM,
            duration: 50,
            total_questions: 25,
            quiz_date: new Date("2026-07-03").toISOString(),
            student_status: "COMPLETED",
            last_score: 80,
            last_correct: 20,
            last_wrong: 5,
            attempt_id: 2,
            is_finished: true,
        },
        {
            uuid: "quiz-uuid-010",
            quiz_title: "Barisan dan Deret",
            difficulty: Difficulty.EASY,
            duration: 30,
            total_questions: 15,
            quiz_date: new Date("2026-07-01").toISOString(),
            student_status: "NOT_STARTED",
            last_score: null,
            last_correct: null,
            last_wrong: null,
            attempt_id: null,
            is_finished: false,
        },
    ],
};
